name: Publish image to registry
on:
  push:
    branches:
      - main

env:
  OCI_REPO: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup go environment
        uses: actions/setup-go@v7

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login --username "${{ github.actor }}" --password-stdin $OCI_REPO

      - name: Build container images and push to container registry
        run: make container container-push
